apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
#https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/gNB_SA_DU.conf
data:
  ric.conf: |
      SM_DIR = "/usr/local/lib/flexric/"
      
      # supported name = NearRT_RIC, E2_Agent, E2_Proxy_Agent, xApp
      Name = "xApp"
      NearRT_RIC_IP = "@RIC_IP_ADDRESS@"
      E42_Port = 36422
      
      # supported name : MAC, RLC, PDCP, GTP, SLICE;
      # supported time: 1_ms, 2_ms, 5_ms, 10_ms, 100_ms, 1000_ms;
      Sub_CUST_SM_List = (
          #{ name = "MAC", time = "1000_ms" },
          #{ name = "RLC", time = "1000_ms" },
          #{ name = "GTP", time = "1000_ms" },          
          { name = "PDCP", time = "1000_ms" }
      )

      Sub_ORAN_SM_List = (
          { name = "RC", time = 0,
            format = 1,
            ran_type = "ngran_gNB", #keep this just in case
            actions = (
                  { id = 1 },
                  { id = 6 },
                  { id = 21528 }
                  )
          },
          { name = "RC", time = 0,
            format = 1,
            ran_type = "ngran_gNB_CUCP",  # NEW entry for CUCP
            actions = (
                  { id = 1 },
                  { id = 6 },
                  { id = 21528 }
                  )
          },
          { name = "KPM", time = 1000,
            format = 4,
            ran_type = "ngran_gNB", #keep this just in case
            actions = (
                  { name = "DRB.PdcpSduVolumeDL" },
                  { name = "DRB.PdcpSduVolumeUL" }
                  )
          },
          { name = "KPM", time = 1000,
            format = 4,
            ran_type = "ngran_gNB_CUCP", # NEW entry for CUCP
            actions = (
                  { name = "DRB.PdcpSduVolumeDL" },
                  { name = "DRB.PdcpSduVolumeUL" }
                  )
          },
          { name = "KPM", time = 1000,
            format = 4,
            ran_type = "ngran_gNB_DU",
            actions = (
                  { name = "DRB.RlcSduDelayDl" }
                  )
          },
          { name = "KPM", time = 1000,
            format = 4,
            ran_type = "ngran_gNB_CU",
            actions = (
                  { name = "DRB.PdcpSduVolumeDL" },
                  { name = "DRB.PdcpSduVolumeUL" }
                  )
          }
      )
      xApp_DB = {
          enable = "OFF"
          ip = "127.0.0.1"
          dir = "/tmp/"
          filename = "testdb"
          username = "xapp" # if using mysql
          password = "eurecom" # if using mysql
      }
