apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
#https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/gNB_SA_DU.conf
data:
  ric.conf: |
      SM_DIR = "/usr/local/lib/flexric/"
      
      # supported name = NearRT_RIC, E2_Agent, E2_Proxy_Agent, xApp
      Name = "xApp"
      NearRT_RIC_IP = "@RIC_IP_ADDRESS@"
      E42_Port = 36422
      
      # supported name : MAC, RLC, PDCP, GTP, SLICE;
      # supported time: 1_ms, 2_ms, 5_ms, 10_ms, 100_ms, 1000_ms;
      Sub_CUST_SM_List = (
          { name = "MAC", time = "10_ms" },
          { name = "RLC", time = "10_ms" },
          { name = "GTP", time = "10_ms" },
          { name = "SLICE", time = "10_ms" },
          { name = "PDCP", time = "10_ms" }
      )
      # Sub_ORAN_SM_List = (
      #     { name = "KPM", time = 10,
      #       format = 1,
      #       ran_type = "ngran_gNB_DU",
      #       actions = (
      #             { name = "DRB.UEThpDl" },
      #             { name = "DRB.UEThpUl" }
      #             )
      #     }
      # )

      xApp_DB = {
          enable = "OFF"
          ip = "127.0.0.1"
          dir = "/tmp/"
          filename = "testdb"
          username = "xapp" # if using mysql
          password = "eurecom" # if using mysql
      }
